const blogs = [
    {
        title: 'How to avoid delibrate foolishness',
        content: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus reiciendis error odit tenetur a dicta amet, illum odio non sequi quia commodi quis? Error asperiores nobis corrupti impedit? Dolor maxime quo omnis nihil quidem dolores sit laboriosam eos accusantium et assumenda, magnam reiciendis nemo? Consequuntur ratione numquam maxime repudiandae fuga, recusandae culpa rerum porro qui optio repellendus a deserunt eaque dolore, provident ducimus ipsam nulla delectus eius assumenda obcaecati laudantium. Eius adipisci earum dolorem expedita, magni, veritatis distinctio consectetur ad laudantium est aperiam a sunt officia. Incidunt inventore, repellat facere fugit eius mollitia quos, similique, saepe ex ducimus optio? Unde, assumenda. Officia esse odit itaque perferendis assumenda voluptatum error? Repellat accusantium consectetur voluptas perferendis unde eveniet alias possimus corporis ipsa veritatis assumenda animi quas labore, asperiores ab, fugiat accusamus? Quas ratione perspiciatis omnis minima. Excepturi numquam, culpa praesentium eius, minus quis nam, est deserunt tempora consequatur eaque. Ex aliquid voluptate iusto ratione voluptas sed, minima, mollitia qui officiis autem veniam quam neque fuga harum optio repellat. Labore nesciunt enim a temporibus ex veniam magni ipsam ab molestias aliquam dolor ullam, distinctio nobis qui sunt exercitationem numquam tenetur omnis. Illo consequuntur mollitia id qui dolores perferendis quidem? Ut quisquam deleniti beatae?",
        author: "chile",
        id: 1,
    },
    {
        title: 'How work hard',
        content: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus reiciendis error odit tenetur a dicta amet, illum odio non sequi quia commodi quis? Error asperiores nobis corrupti impedit? Dolor maxime quo omnis nihil quidem dolores sit laboriosam eos accusantium et assumenda, magnam reiciendis nemo? Consequuntur ratione numquam maxime repudiandae fuga, recusandae culpa rerum porro qui optio repellendus a deserunt eaque dolore, provident ducimus ipsam nulla delectus eius assumenda obcaecati laudantium. Eius adipisci earum dolorem expedita, magni, veritatis distinctio consectetur ad laudantium est aperiam a sunt officia. Incidunt inventore, repellat facere fugit eius mollitia quos, similique, saepe ex ducimus optio? Unde, assumenda. Officia esse odit itaque perferendis assumenda voluptatum error? Repellat accusantium consectetur voluptas perferendis unde eveniet alias possimus corporis ipsa veritatis assumenda animi quas labore, asperiores ab, fugiat accusamus? Quas ratione perspiciatis omnis minima. Excepturi numquam, culpa praesentium eius, minus quis nam, est deserunt tempora consequatur eaque. Ex aliquid voluptate iusto ratione voluptas sed, minima, mollitia qui officiis autem veniam quam neque fuga harum optio repellat. Labore nesciunt enim a temporibus ex veniam magni ipsam ab molestias aliquam dolor ullam, distinctio nobis qui sunt exercitationem numquam tenetur omnis. Illo consequuntur mollitia id qui dolores perferendis quidem? Ut quisquam deleniti beatae?",
        author: "praise",
        id: 2,
    },
    {
        title: 'All you need to know about EJS view Engine',
        content: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus reiciendis error odit tenetur a dicta amet, illum odio non sequi quia commodi quis? Error asperiores nobis corrupti impedit? Dolor maxime quo omnis nihil quidem dolores sit laboriosam eos accusantium et assumenda, magnam reiciendis nemo? Consequuntur ratione numquam maxime repudiandae fuga, recusandae culpa rerum porro qui optio repellendus a deserunt eaque dolore, provident ducimus ipsam nulla delectus eius assumenda obcaecati laudantium. Eius adipisci earum dolorem expedita, magni, veritatis distinctio consectetur ad laudantium est aperiam a sunt officia. Incidunt inventore, repellat facere fugit eius mollitia quos, similique, saepe ex ducimus optio? Unde, assumenda. Officia esse odit itaque perferendis assumenda voluptatum error? Repellat accusantium consectetur voluptas perferendis unde eveniet alias possimus corporis ipsa veritatis assumenda animi quas labore, asperiores ab, fugiat accusamus? Quas ratione perspiciatis omnis minima. Excepturi numquam, culpa praesentium eius, minus quis nam, est deserunt tempora consequatur eaque. Ex aliquid voluptate iusto ratione voluptas sed, minima, mollitia qui officiis autem veniam quam neque fuga harum optio repellat. Labore nesciunt enim a temporibus ex veniam magni ipsam ab molestias aliquam dolor ullam, distinctio nobis qui sunt exercitationem numquam tenetur omnis. Illo consequuntur mollitia id qui dolores perferendis quidem? Ut quisquam deleniti beatae?",
        author: "Robert",
        id: 3,
    },
    {
        title: 'Uses of React useState Hook',
        content: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus reiciendis error odit tenetur a dicta amet, illum odio non sequi quia commodi quis? Error asperiores nobis corrupti impedit? Dolor maxime quo omnis nihil quidem dolores sit laboriosam eos accusantium et assumenda, magnam reiciendis nemo? Consequuntur ratione numquam maxime repudiandae fuga, recusandae culpa rerum porro qui optio repellendus a deserunt eaque dolore, provident ducimus ipsam nulla delectus eius assumenda obcaecati laudantium. Eius adipisci earum dolorem expedita, magni, veritatis distinctio consectetur ad laudantium est aperiam a sunt officia. Incidunt inventore, repellat facere fugit eius mollitia quos, similique, saepe ex ducimus optio? Unde, assumenda. Officia esse odit itaque perferendis assumenda voluptatum error? Repellat accusantium consectetur voluptas perferendis unde eveniet alias possimus corporis ipsa veritatis assumenda animi quas labore, asperiores ab, fugiat accusamus? Quas ratione perspiciatis omnis minima. Excepturi numquam, culpa praesentium eius, minus quis nam, est deserunt tempora consequatur eaque. Ex aliquid voluptate iusto ratione voluptas sed, minima, mollitia qui officiis autem veniam quam neque fuga harum optio repellat. Labore nesciunt enim a temporibus ex veniam magni ipsam ab molestias aliquam dolor ullam, distinctio nobis qui sunt exercitationem numquam tenetur omnis. Illo consequuntur mollitia id qui dolores perferendis quidem? Ut quisquam deleniti beatae?",
        author: "Ade",
        id: 4,
    },
];


module.exports = blogs;